### ISSUE TITLE
Suggestion Filter by Name/Entitys

### ISSUE THREAD

**Issue by Fundryi** [EBro912/SpectateEnemies#1]
Right now it spectates Docile Locust Bees and the Manticoils which isn't that good/usefull.
Also would recommend adding a hotkey to switch back to the player1 so when you click Mous1 you switch again to player2,3,4 

Right now you can't got like Player1 -> Player2 -> Player3 -> Player2 -> Player1, like revert back like most other games do it (because Right Mousebutton is Vote Leave)

**Comment by EBro912** [comment]
I plan on adding an option to disable passive enemies next update.

As for your other suggestion, did you mean you wanted a hotkey to immediately switch back to a player instead of having to click through all of the enemies?

**Comment by Fundryi** [comment]
Either a key that switches you to Player1 so when you left click it goes again from the beginning.
Or
Just make a toggle key with Indicator that you are no in "Spectator Mode: Player" or "Spectator Mode: Enemy" :o

**Comment by EBro912** [comment]
Resolved as of v1.2
