### ISSUE TITLE
[Request]  Option to turn off the tooltip text on the hud

### ISSUE THREAD

**Issue by PixelIndieDev** [EBro912/SpectateEnemies#10]
The reason why is that if you combine this mod with the dead and bored mod (which lets you talk as the enemies), you can pull pranks on your friends by letting them think that the Skinwalkers mod is scarily accurate with its responses. But with the tooltip text in the spectate hud, they can kinda get a suspicion that another mod is in play.

I share my Lethal Company mod via a profile file from r2modman and tell them not to look at the mods (so they shouldn't know that another mod is in play), so it would be funny if the illusion of amazing responses of the enemies would last longer.

**Comment by EBro912** [comment]
This is now a config option as of v2.3, simply open the .cfg file and change `Hide Controls` to `true`.
