### ISSUE TITLE
Another NulLReferenceException bug

### ISSUE THREAD

**Issue by ThatKnifeGuy** [EBro912/SpectateEnemies#12]
I loaded my save file then my log went crazy with those messages, it also kept going when i left to the main menu.
![image](https://github.com/EBro912/SpectateEnemies/assets/98409495/97a0d9b7-c82d-4c57-8cfa-a09c0b79cbe9)

**Comment by EBro912** [comment]
That error is from the SpectateEnemiesZoomFix mod, which is a seperate mod that aimed to fix the zoom feature. Since that mod is now implemented into SpectateEnemies itself you no longer need that mod, so removing it should make that error go away.

**Comment by ThatKnifeGuy** [comment]
Ooooh alright thanks!
