### ISSUE TITLE
Unable to spectate enemies 

### ISSUE THREAD

**Issue by zdeztroy** [EBro912/SpectateEnemies#2]
Have the latest version 1.3.0 version of SpectateEnemies and unable to spectate when in game. Installed through thunderstore but isn't working for me. I can use the flashlight I spectate someone so I know some part of the mod works, but whenever I press E(my interact key) I am unable to spectate enemies. Works for my friends in my lobby though. Also previous versions have not worked for me either.

**Comment by EBro912** [comment]
Are there any errors in your console/log files? Keep in mind that if no enemies are available to spectate it will not work either.

**Comment by zdeztroy** [comment]
Not sure what to look out for in the log files but yes enemies have spawned and I am unable to spectate the enemies. My friends in the same lobby can spectate them but it doesn't show up for me after pressing e.  I also have a friend with the same issue and have tried reinstalling the mod and the game to fix it but unable to.

**Comment by EBro912** [comment]
Try the latest version and let me know if you're still running into issues

**Comment by zdeztroy** [comment]
still the same issues, when i press e it just switches to a teammate

**Comment by Xylzlol** [comment]
i have the same issue, pressing E just switches to another player on my team, and then stops doing anything at all, even if there are enemies to spectate

i think it may be a host issue, because as OP said all my friends can use it no problem

**Comment by Xylzlol** [comment]
and no, nothing happens in console

**Comment by zdeztroy** [comment]
> i have the same issue, pressing E just switches to another player on my team, and then stops doing anything at all, even if there are enemies to spectate
> 
> i think it may be a host issue, because as OP said all my friends can use it no problem

sorry should have updated the issue before hand but after doing a fresh install of the game + fresh install of thunderstore it solved the issue

**Comment by Xylzlol** [comment]
alright thanks i'll try that out

**Comment by EBro912** [comment]
Going to mark this as resolved as there have been no updates in 2 weeks, try the latest version and create another issue if you still run into this bug.
