### ISSUE TITLE
Game version 45 megathread

### ISSUE THREAD

**Issue by EBro912** [EBro912/SpectateEnemies#3]
Known Issues
- Mod throws an error on startup
- You cannot click through available enemies
- Some information text does not display

Working on fixes asap!

**Comment by EBro912** [comment]
Should be working as of Release v1.4, I will leave this thread open in case there are any more issues.

**Comment by TwoPointInfinity** [comment]
not sure if conflict but i cant switch to enemies, just stays on players.
