### ISSUE TITLE
Bug - Spectate enemies stopped working and does not generate a config file

### ISSUE THREAD

**Issue by santocraft** [EBro912/SpectateEnemies#5]
![image_2023-12-31_004547035](https://github.com/EBro912/SpectateEnemies/assets/40782597/f320b6cc-0d1b-4595-a260-9932885d82ed)
It was working fine before, now it doesn't generate a config file (I deleted it cause it was empty) and it just doesn't work at all.

**Comment by EBro912** [comment]
This is an issue when the mod tries to spectate masked players, I am away at the moment but I do know why this happens, so I will fix it as soon as I can.

**Comment by EBro912** [comment]
Should be fixed as of v2.1, make another issue if the bug persists.

**Comment by santocraft** [comment]
Update not available in r2modman yet
