### ISSUE TITLE
[Bug] Dead bracken causes NullRef

### ISSUE THREAD

**Issue by OoLunar** [EBro912/SpectateEnemies#6]
Once a player manages to successfully kill a bracken, dead players can no longer spectate enemies. When the dead players attempt to spectate anyways, the camera will instead freeze in place while the console is spammed with `NullReferenceException`s. It is assumed that the last spectated (or randomly chosen) enemy must be the dead bracken for this bug to occur. Unfortunately I was unable to grab the stack trace, however it was only a single line.

Thank you for making the mod!

**Comment by skylarkblue1** [comment]
It seems to be any dead enemy, dead centipede also causes it. Attaching a couple screenshots from my console that was being spammed to hell and back.
![Lethal_Company_UXHxxGa68o](https://github.com/EBro912/SpectateEnemies/assets/15182062/7e134b24-fc56-42bd-9d23-fb40b8bff2be)
![Lethal_Company_8iRAadNomS](https://github.com/EBro912/SpectateEnemies/assets/15182062/162c0877-30cb-4fc6-9325-214cb57bcff4)

**Comment by EBro912** [comment]
The first image is a vanilla error, but the second one is definitely a bug. Thanks for reporting, I'll look into that for next update

**Comment by skylarkblue1** [comment]
> The first image is a vanilla error, but the second one is definitely a bug. Thanks for reporting, I'll look into that for next update

Might be part of it? It was spamming that only when the bug triggered

**Comment by EBro912** [comment]
This should be fixed as of the latest release, closing for now
