### ISSUE TITLE
[Request] Option to turn off flashlight option

### ISSUE THREAD

**Issue by bubin7766** [EBro912/SpectateEnemies#9]
Reason for this would be better compatibility with [enhancedspectator](https://thunderstore.io/c/lethal-company/p/PXC/EnhancedSpectator/)
The main reason I’m using this mod though is because when I have [Eladshud](https://thunderstore.io/c/lethal-company/p/EladNLG/EladsHUD/) installed the sprint meter is still shown in spectator mode overlaying on top of spectator icons and somehow this mod fixes that plus the night vision and clock overlay is nice
If native compatibility could be added to just hide your extra flashlight toggle when this mod is enabled that would be awesome :)

**Comment by EBro912** [comment]
I didn't know that mod exists, but thank for for the suggestion! I'll see what I can do about that in the next update

**Comment by EBro912** [comment]
I added an option to hide the controls in v2.3, just change `HideControls` in the .cfg file to `true`. Also, if you want to turn off the flashlight completely, you can unbind it in the in-game control settings to disable it entirely.
